kumuluzee:
  name: profileservice
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/profileservice
    connection-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: skiprope
    max-pool-size: 2
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/profileservice
      disk-space-health-check:
        threshold: 100000000

  discovery:
    etcd:
      hosts: http://localhost:2379

  config:
    etcd:
      hosts: http://localhost:2379

# Settings and configurations
skiprope-configs:
  health:
    etcd-url: http://localhost:2379/health
  show-email: True




