kumuluzee:
  name: profileservice
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/profileservice
    connection-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: skiprope
    max-pool-size: 2

  discovery:
    consul:
      agent: http://localhost:8500

  config:
    consul:
      agent: http://localhost:8500

# Settings and configurations
skiprope-configs:
  show-email: True




