kind: Service
apiVersion: v1
metadata:
  name: profileservice
spec:
  selector:
    app: profileservice
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileservice-deployment
  labels:
    app: profileservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profileservice
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
      - name: profileservice
        image: skiprope/profileservice:latest
        ports:
        - containerPort: 8081
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-ps:5432/postgres
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: postgres
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: skiprope
          - name: SKIPROPECONFIGS_HEALTH_ETCDURL
            value: http://etcd:2379/health
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://profileservice:8081
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: skiprope
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3