kind: Service
apiVersion: v1
metadata:
  name: profileservice
spec:
  selector:
    app: profileservice
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileservice-deployment
  labels:
    app: profileservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profileservice
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
      - name: profileservice
        image: skiprope/profileservice:latest
        ports:
        - containerPort: 8081
        env:
          - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
            value: http://consul:8500  
          - name: KUMULUZEE_CONFIG_CONSUL_AGENT
            value: http://consul:8500
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://manny.db.elephantsql.com:5432/fckauhpq
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: fckauhpq
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: hH88MKljIGnHZ3jQYbQLt-C2qGzh-Qbx
        