kumuluzee:
  name: profileservice
  version: 1.0.0

  env:
    name: dev

  server:
    http:
      port: 8081

  datasources:
  - jndi-name: jdbc/profileservice
    connection-url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: postgres
    max-pool-size: 10

  config:
    consul:
      agent: http://192.168.99.100:8500

# Settings and configurations
skiprope-configs:
  show-email: True




